### ISSUE TITLE
2951 Goodman's SE Block - to-do list

### ISSUE THREAD

**Issue by chrisbauermh** [millerhare/2951-Goodmans-Fields-SE-Block#1]
First draft to-do, please amend as required (currently awaiting brochure)

 * [ ]  Data @chthonicionic 

 * [ ] CSS 
   * [ ] colours
   * [ ] layout tweaks
   * [ ] layouts:
     * [ ] iPad 1024px
     * [ ] 1280px
     * [ ] 1920px 

 * [ ] Berkeley Group section (@chrisbauermh)
   * [ ] copy
   * [ ] updated logos? 

 * [ ] Location (@chrisbauermh)
   * [ ] copy
   * [ ] images
   * [ ] map

 * [ ] Development  (@chrisbauermh)
   * [ ] copy
   * [ ] images
   * [ ] siteplan

 * [ ] Apartments  (@chrisbauermh)
   * [ ] copy
   * [ ] images
   * [ ] Specs

 * [ ] Choose an apartment
   * [ ] apartment data (@chthonicionic)
   * [ ] plans (@chrisbauermh)
   * [ ] images (@chrisbauermh)
   * [ ] cuts
      * [ ] first renders (@Lareon)
      * [ ] final versions (@Lareon)
   * [ ] masks (@Lareon)
   * [ ] views (@chthonicionic)
     * [ ] view photography (@chthonicionic/@chrisbauermh)
     * [ ] check view metadata (@chthonicionic)
 
* [ ] Films (@chrisbauermh)

* [ ] Gallery (@chrisbauermh/@chthonicionic)
  * [ ] Images (@chrisbauermh)

**Comment by chrisbauermh** [comment]
Previous Goodman's interactive opied/set-up in repo
